name: "Create Coder Task"
description: "Create a Coder Task for a GitHub user, with support for issue commenting"
author: "Coder Technologies Inc. <https://coder.com>"

branding:
  icon: arrow-down-circle
  color: purple

inputs:
  # Required inputs
  coder-task-prompt:
    description: "Prompt/instructions to send to the task"
    required: true

  coder-token:
    description: "Coder session token for authentication"
    required: true

  coder-url:
    description: "Coder deployment URL"
    required: true

  coder-template-name:
    description: "Coder template to use for workspace"
    required: true

  github-issue-url:
    description: "GitHub issue URL to link this task to"
    required: true

  github-token:
    description: "GitHub token for API operations"
    required: true

  github-user-id:
    description: "GitHub user ID to create task for"
    required: true

  # Optional inputs
  coder-organization:
    description: "Coder organization name"
    required: false
    default: "default"

  coder-task-name-prefix:
    description: "Prefix for task name"
    required: false
    default: "gh"

  coder-template-preset:
    description: "Template preset to use (optional)"
    required: false

  comment-on-issue:
    description: "Whether to comment on the GitHub issue"
    required: false
    default: "true"

outputs:
  coder-username:
    description: "The Coder username resolved from GitHub user"

  task-name:
    description: "The task name"

  task-url:
    description: "The URL to view the task in Coder"

  task-created:
    description: "Whether the task was newly created (true) or already existed (false)"

runs:
  using: "node20"
  main: "dist/index.js"
